steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/shadow9911/2005godina.git']
    dir: /workspace

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gsutil'
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/project/*'
      - 'gs://alex4e-kod/'

options:
  logging: CLOUD_LOGGING_ONLY
