steps:
  # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com//shadow9911/2005-godina.git']
    dir: /workspace

  # Step 2: Copy the cloned files to the Google Cloud Storage bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gsutil'
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/project/*'
      - 'gs://alex4e-kod/'
options:
    logging: NONE
      
timeout: '30s'  # 10-minute timeout
