steps:
  # Step 1: Clone the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/shadow9911/2005godina.git']
    dir: /workspace

  # Step 2: Zip the cloned files
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace/2005godina
        zip -r /workspace/2005godina.zip .

  # Step 3: Upload the zipped file to the Google Cloud Storage bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gsutil'
      - 'cp'
      - '/workspace/2005godina.zip'
      - 'gs://alex4e-kod/2005godina.zip'
      
  # Step 4: Get the latest instance template name
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-latest-instance-template'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        latest_template=$(gcloud compute instance-templates list --sort-by=~creationTimestamp --limit=1 --format="value(name)")
        echo "LATEST_TEMPLATE_NAME=$latest_template" >> /workspace/env_vars.txt

  # Step 5: Trigger a rolling update on the managed instance group using the latest template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/env_vars.txt
        gcloud compute instance-groups managed rolling-action start-update alex4e-instance-group --zone=us-central1 --version=template=$LATEST_TEMPLATE_NAME


options:
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'  # 10-minute timeout
